# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectSurveillance', '0002_projectdetail_workstepid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetail',
            name='detailtypeid',
            field=models.ForeignKey(db_column='DetailTypeID', null=True, on_delete=django.db.models.deletion.CASCADE, to='ProjectSurveillance.DetailType'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='projectid',
            field=models.ForeignKey(db_column='ProjectID', null=True, on_delete=django.db.models.deletion.CASCADE, to='ProjectSurveillance.Project'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='userid',
            field=models.ForeignKey(db_column='UserID', null=True, on_delete=django.db.models.deletion.CASCADE, to='ProjectSurveillance.VSUser'),
        ),
    ]
