# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 17:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectSurveillance', '0003_auto_20171102_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdetail',
            name='workstepid',
        ),
        migrations.DeleteModel(
            name='Workstep',
        ),
    ]
