# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-03 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectSurveillance', '0004_auto_20171102_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectActivity',
            fields=[
                ('activityid', models.AutoField(db_column='ActivityID', primary_key=True, serialize=False)),
                ('actionneededby', models.IntegerField(db_column='ActionNeededBy', null=True)),
                ('datelogged', models.DateTimeField(auto_now_add=True, db_column='DateLogged')),
                ('note', models.TextField(db_column='Note', max_length=4000, null=True)),
                ('archive', models.NullBooleanField(db_column='Archive')),
                ('loggedby', models.ForeignKey(db_column='LoggedBy', on_delete=django.db.models.deletion.CASCADE, to='ProjectSurveillance.VSUser')),
                ('projectid', models.ForeignKey(db_column='ProjectID', on_delete=django.db.models.deletion.CASCADE, to='ProjectSurveillance.Project')),
            ],
            options={
                'db_table': 'VS_Project_Activity',
            },
        ),
        migrations.CreateModel(
            name='WorkPhase',
            fields=[
                ('phaseid', models.AutoField(db_column='PhaseID', primary_key=True, serialize=False)),
                ('phase', models.CharField(db_column='Phase', max_length=255)),
                ('phaseorder', models.IntegerField(db_column='PhaseOrder', null=True)),
            ],
            options={
                'db_table': 'VS_Work_Phase',
            },
        ),
        migrations.CreateModel(
            name='WorkStep',
            fields=[
                ('stepid', models.AutoField(db_column='StepID', primary_key=True, serialize=False)),
                ('step', models.CharField(db_column='Step', max_length=2000, null=True)),
                ('note', models.TextField(db_column='Note', max_length=4000, null=True)),
                ('archive', models.NullBooleanField(db_column='Archive')),
                ('phaseid', models.ForeignKey(db_column='PhaseID', on_delete=django.db.models.deletion.CASCADE, to='ProjectSurveillance.WorkPhase')),
            ],
            options={
                'db_table': 'VS_Work_Step',
            },
        ),
        migrations.AddField(
            model_name='projectactivity',
            name='workstepid',
            field=models.ForeignKey(db_column='WorkstepID', on_delete=django.db.models.deletion.CASCADE, to='ProjectSurveillance.WorkStep'),
        ),
    ]
