# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectSurveillance', '0005_auto_20171103_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='projectcatid',
        ),
        migrations.AddField(
            model_name='project',
            name='accesslinkid',
            field=models.IntegerField(blank=True, db_column='AccessLinkID', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='alternateid',
            field=models.CharField(db_column='AlternateID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='phaseid',
            field=models.ForeignKey(db_column='PhaseID', null=True, on_delete=django.db.models.deletion.CASCADE, to='ProjectSurveillance.WorkPhase'),
        ),
    ]
