# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 18:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectSurveillance', '0006_auto_20171109_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workstep',
            name='phaseid',
        ),
    ]
