# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectSurveillance', '0009_detailtype_drive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectactivity',
            name='datelogged',
            field=models.DateField(db_column='DateLogged'),
        ),
    ]
